### ISSUE TITLE
2FA not working

### ISSUE THREAD

**Issue by Bluscream** [Luigifan/DiscordSharpOverwolf#1]
I can't log in cause there is no Two Factor Authorization Support in DiscordSharp :(

**Comment by suicvne** [comment]
discordsharp outdated

**Comment by Bluscream** [comment]
So it's dead?

**Comment by suicvne** [comment]
yes, https://github.com/NaamloosDT/DSharpPlus this is the successor

**Comment by Bluscream** [comment]
Would you update your app to use it?

**Comment by suicvne** [comment]
no, i don't even have a Windows PC anymore. i'm full time OS X. if I ever decide to resurrect a PC again I may but as of right now I won't be.
